on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  check_if_env_changed:
    runs-on: ubuntu-latest
    outputs:
      docs_changed: ${{ steps.check_file_changed.outputs.docs_changed }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - shell: pwsh
      id: check_file_changed
      run: |
        $diff = git diff --name-only HEAD^ HEAD
        $SourceDiff = $diff | Where-Object { $_ -match '^.env' }
        $HasDiff = $SourceDiff.Length -gt 0
        Write-Host "::set-output name=docs_changed::$HasDiff"
    
  comment:
    runs-on: ubuntu-latest
    needs: [ check_if_env_changed ]
    if: needs.check_if_env_changed.outputs.docs_changed == 'True'
    steps:
      - uses: actions/github-script@v5
        with:
          github-token: ${{secrets.PR_COMMENT_GITHUB_TOKEN}}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'There was a change on the env file, ADD THE NEW ENVIRONMENT KEY BEFORE MERGING!!!!!'
            })
